Repository NordicSemiconductor/nRF-IEEE-802.15.4-radio-driver, pull requests merged in 2018-03, with the labels that each got.

#80 Prevent notification of invalid frame on dst addr mismatch
  src/mac_features/nrf_802154_filter.c
  src/mac_features/nrf_802154_filter.h
  src/nrf_802154_core.c
Labels: bug

#82 Add MDK, CMSIS and SoftDevice headers.
  external/cmsis/arm_common_tables.h
  external/cmsis/arm_const_structs.h
  external/cmsis/arm_math.h
  external/cmsis/cmsis_armcc.h
  external/cmsis/cmsis_armcc_V6.h
  external/cmsis/cmsis_gcc.h
  external/cmsis/core_cm0.h
  external/cmsis/core_cm0plus.h
  external/cmsis/core_cm3.h
  external/cmsis/core_cm4.h
  external/cmsis/core_cm7.h
  external/cmsis/core_cmFunc.h
  external/cmsis/core_cmInstr.h
  external/cmsis/core_cmSimd.h
  external/cmsis/core_sc000.h
  external/cmsis/core_sc300.h
  external/mdk/compiler_abstraction.h
  external/mdk/nrf.h
  external/mdk/nrf51_to_nrf52840.h
  external/mdk/nrf52.h
  external/mdk/nrf52840.h
  external/mdk/nrf52840_bitfields.h
  external/mdk/nrf52840_peripherals.h
  external/mdk/nrf52_bitfields.h
  external/mdk/nrf52_name_change.h
  external/mdk/nrf52_to_nrf52840.h
  external/mdk/nrf_peripherals.h
  external/mdk/system_nrf52840.h
  external/softdevice/s140/headers/ble.h
  external/softdevice/s140/headers/ble_err.h
  external/softdevice/s140/headers/ble_gap.h
  external/softdevice/s140/headers/ble_gatt.h
  external/softdevice/s140/headers/ble_gattc.h
  external/softdevice/s140/headers/ble_gatts.h
  external/softdevice/s140/headers/ble_hci.h
  external/softdevice/s140/headers/ble_l2cap.h
  external/softdevice/s140/headers/ble_ranges.h
  external/softdevice/s140/headers/ble_types.h
  external/softdevice/s140/headers/nrf52/nrf_mbr.h
  external/softdevice/s140/headers/nrf_error.h
  external/softdevice/s140/headers/nrf_error_sdm.h
  external/softdevice/s140/headers/nrf_error_soc.h
  external/softdevice/s140/headers/nrf_nvic.h
  external/softdevice/s140/headers/nrf_sdm.h
  external/softdevice/s140/headers/nrf_soc.h
  external/softdevice/s140/headers/nrf_svc.h
  external/softdevice/s140/s140_nrf52840_6.0.0-6.alpha_license-agreement.txt
  external/softdevice/s140/s140_nrf52840_6.0.0-6.alpha_release-notes.pdf
Labels: enhancement

#81 Add functions to calculate ED and LQI values based on hardware tests
  src/nrf_802154.c
  src/nrf_802154_config.h
  src/nrf_802154_const.h
  src/nrf_802154_core.c
Labels: bug

#84 reviewed language and doxygen tagging for external API files
  README.md
  src/nrf_802154.h
  src/nrf_802154_config.h
  src/nrf_802154_types.h
Labels: docs

#85 Fix build on IAR
  src/nrf_802154_core.c
Labels: bug

#83 [raal] SoftDevice RAAL clean up
  src/nrf_802154_debug.h
  src/raal/softdevice/nrf_raal_softdevice.c
  tools/event_decoder/decoder.html
Labels: bug, enhancement

#86 Prevent enabling RADIO IRQ in critical section.
  src/nrf_802154_core.c
Labels: bug

#87 Correct RSSI, ED, LQI, CCA ED threshold values with temperature
  nRF-IEEE-802.15.4-radio-driver.packsc
  src/nrf_802154.c
  src/nrf_802154.h
  src/nrf_802154_core.c
  src/nrf_802154_rssi.c
  src/nrf_802154_rssi.h
  src/platform/temperature/nrf_802154_temperature.h
  src/platform/temperature/nrf_802154_temperature_none.c
Labels: enhancement

#90 Fix IAR 7.80 warnings
  src/timer_scheduler/nrf_802154_timer_sched.c
Labels: bug

#91 Notify failure to mac_feature modules when entering critical section fails.
  src/nrf_802154_request_direct.c
  src/nrf_802154_request_swi.c
  src/nrf_802154_swi.c
Labels: bug

#92 Notify received frame when TX ACK is terminated
  src/nrf_802154_core.c
Labels: bug

#93 Fix race in exiting timeslot procedure
  src/nrf_802154_core.c
  src/nrf_802154_priority_drop.h
  src/nrf_802154_priority_drop_direct.c
  src/nrf_802154_priority_drop_swi.c
  src/nrf_802154_swi.c
  src/nrf_802154_swi.h
Labels: bug
