Repository NordicSemiconductor/nRF-IEEE-802.15.4-radio-driver, pull requests merged in 2018-08, with the labels that each got.

#139 Add priorities to API of the RSCH module
  nRF-IEEE-802.15.4-radio-driver.packsc
  src/mac_features/nrf_802154_delayed_trx.c
  src/nrf_802154_core.c
  src/nrf_802154_critical_section.c
  src/nrf_802154_critical_section.h
  src/rsch/nrf_802154_rsch.c
  src/rsch/nrf_802154_rsch.h
  src/rsch/nrf_802154_rsch_crit_sect.c
  src/rsch/nrf_802154_rsch_crit_sect.h
Labels: enhancement

#143 Implementing nrf_802154_sleep_if_idle() function.
  src/nrf_802154.c
  src/nrf_802154.h
  src/nrf_802154_types.h
Labels: enhancement

#142 Fix rounding of LP Timer trigger time
  src/mac_features/nrf_802154_delayed_trx.c
  src/platform/lp_timer/nrf_802154_lp_timer_nodrv.c
Labels: bug

#140 Prevent reentrancy of SWI notifications
  src/nrf_802154_swi.c
Labels: bug

#148 Fix double notification of received frame on timeslot end during tx ack
  src/nrf_802154_core.c
Labels: bug

#150 Optimize timing calculations
  src/nrf_802154_utils.h
  src/platform/lp_timer/nrf_802154_lp_timer_nodrv.c
  src/raal/softdevice/nrf_raal_softdevice.c
Labels: enhancement

#151 Fix GCC warnings
  src/nrf_802154_core.c
  src/nrf_802154_rsch.c
Labels: bug

#153 Fix direct Front-End module pins reset
  src/fem/nrf_fem_control.c
Labels: bug

#141 Release notes 1.2.0
  release_notes/nrf_802154_1.2.0.md
Labels: docs

#154 Fix build with CSMA-CA disabled
  src/mac_features/nrf_802154_csma_ca.c
Labels: bug

#155 Preserve RTC interrupt status while leaving critical sections
  src/nrf_802154_request_swi.c
  src/nrf_802154_utils.h
  src/platform/lp_timer/nrf_802154_lp_timer_nodrv.c
Labels: enhancement
