Repository NordicSemiconductor/nRF-IEEE-802.15.4-radio-driver, pull requests merged in 2018-12, with the labels that each got.

#178 Add confirmation of ended timeslot
  src/nrf_802154.c
  src/nrf_802154_config.h
  src/nrf_802154_core.c
  src/rsch/nrf_802154_rsch.c
  src/rsch/nrf_802154_rsch.h
  src/rsch/raal/nrf_raal_api.h
  src/rsch/raal/simulator/nrf_raal_simulator.c
  src/rsch/raal/single_phy/single_phy.c
  src/rsch/raal/softdevice/nrf_raal_softdevice.c
Labels: enhancement

#180 Provide more build configurations to enhance on-target tests
  nRF-IEEE-802.15.4-radio-driver.packsc
Labels: enhancement

#175 Add delayed RX operation support.
  src/mac_features/nrf_802154_delayed_trx.c
  src/mac_features/nrf_802154_delayed_trx.h
  src/nrf_802154.c
  src/nrf_802154.h
  src/nrf_802154_core.c
  src/nrf_802154_core_hooks.c
  src/nrf_802154_core_hooks.h
  src/nrf_802154_debug.h
  src/nrf_802154_types.h
  src/timer_scheduler/nrf_802154_timer_sched.c
  src/timer_scheduler/nrf_802154_timer_sched.h
  test/unit tests/fsm_frame_filtering/unity_test.c
  tools/event_decoder/decoder.html
Labels: enhancement

#183 [build] cleanup: move libraries to separated component
  nRF-IEEE-802.15.4-radio-driver.packsc
Labels: enhancement

#181 [raal] do not assert on previous SoftDevices
  src/rsch/raal/softdevice/nrf_raal_softdevice.c
Labels: enhancement

#182 [raal] fix logging in SoftDevice arbiter client
  src/rsch/raal/softdevice/nrf_raal_softdevice.c
Labels: bug

#186 [build] move component to appropriate repository
  nRF-IEEE-802.15.4-radio-driver.packsc
Labels: bug

#185 [docs] release notes 1.2.3
  release_notes/nrf_802154_1.2.3.md
Labels: docs
