Repository NordicSemiconductor/nRF-IEEE-802.15.4-radio-driver, pull requests merged in 2019-05, with the labels that each got.

#228 Update nrf_802154_core.c - bugfix the channel_set function
  src/nrf_802154_core.c
  test/unit tests/fsm_ed/unity_test.c
Labels: bug

#229 Update nrf_802154_core.c - added tx power setting to continuous carrier initialization
  src/nrf_802154_core.c
  test/unit tests/fsm_cont_carrier/unity_test.c
Labels: enhancement

#236 Add BKPT instruction to assert handler to ease interactive debugging
  src/nrf_802154_debug.c
Labels: enhancement

#231 Do not hang in timer synchronization init without optimizations.
  src/platform/lp_timer/nrf_802154_lp_timer_nodrv.c
Labels: bug

#237 Add nRF52811 to supported SoCs list in README.md
  README.md
Labels: docs

#238 Add random number abstraction layer in platform directory
  nRF-IEEE-802.15.4-radio-driver.packsc
  src/mac_features/nrf_802154_csma_ca.c
  src/nrf_802154.c
  src/nrf_802154.h
  src/platform/random/nrf_802154_random.h
  src/platform/random/nrf_802154_random_stdlib.c
Labels: enhancement

#242 Set delayed RX state with exclusive read/write operations.
  src/mac_features/nrf_802154_delayed_trx.c
Labels: bug
